CREATE TABLE user (
  Id INT NOT NULL AUTO_INCREMENT,
  UserName VARCHAR(50) NOT NULL,
  Password VARCHAR(50) NOT NULL,
  Active TINYINT NOT NULL,
  CreateDate DATETIME NOT NULL,
  CreatedBy VARCHAR(40) NOT NULL,
  LastUpdate DATETIME NOT NULL,
  LastUpdateBy VARCHAR(40) NOT NULL,
  PRIMARY KEY (Id),
  UNIQUE INDEX Id_UNIQUE (Id ASC) VISIBLE);
